version: '2'
services:
  web:
    build: .
    image: flaskrqexample
    container_name: flaskrqexample_web
    environment:
      LOCAL_SETTINGS: /app/settings.cfg
    command: python manage.py runserver --host 0.0.0.0
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    depends_on:
    - redis
  worker:
    image: flaskrqexample
    container_name: flaskrqexample_worker
    environment:
      LOCAL_SETTINGS: /app/settings.cfg
    command: python manage.py runworker
    volumes:
    - .:/app
    depends_on:
    - redis
  redis:
    image: redis:3.2
